
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package lexer;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int BYTE = 115;
  public static final int ASC = 61;
  public static final int TB = 159;
  public static final int FLOAT = 90;
  public static final int UNPIVOT = 35;
  public static final int Igual = 29;
  public static final int BLOB = 102;
  public static final int GO = 16;
  public static final int FILEGROWTH = 153;
  public static final int Division = 43;
  public static final int Porcentaje = 44;
  public static final int LIKE = 64;
  public static final int INCLUDE = 92;
  public static final int KEYSET = 145;
  public static final int ORDER = 52;
  public static final int CREATE = 94;
  public static final int GB = 158;
  public static final int BEGIN = 133;
  public static final int IMAGE = 108;
  public static final int NAMES = 88;
  public static final int VARCHAR = 104;
  public static final int INTO = 3;
  public static final int TYPE_WARNING = 151;
  public static final int Punto = 13;
  public static final int LOCAL = 140;
  public static final int WHERE = 68;
  public static final int REMOTE = 33;
  public static final int Doble_numeral = 132;
  public static final int REAL = 109;
  public static final int DYNAMIC = 146;
  public static final int ESCAPE = 55;
  public static final int VALUES = 5;
  public static final int MODIFY = 95;
  public static final int IDENTITY = 72;
  public static final int ADD = 97;
  public static final int Parentesis_de_cierre = 8;
  public static final int HAVING = 53;
  public static final int CURSOR = 112;
  public static final int BIT = 103;
  public static final int NULL = 12;
  public static final int EOF = 0;
  public static final int INT = 125;
  public static final int SMALLINT = 128;
  public static final int SAVEPOINT = 137;
  public static final int MAX = 119;
  public static final int Corchete_de_cierre = 122;
  public static final int Suma = 40;
  public static final int ACTION = 83;
  public static final int SIZE = 91;
  public static final int USER = 120;
  public static final int DROP = 99;
  public static final int CHAR = 100;
  public static final int NCHAR = 118;
  public static final int OR = 67;
  public static final int Numeral = 131;
  public static final int COMMIT = 136;
  public static final int NAME = 86;
  public static final int ON = 27;
  public static final int UNIQUE = 77;
  public static final int AND = 54;
  public static final int BINARY = 101;
  public static final int CURRENT = 96;
  public static final int COUNT = 70;
  public static final int Mayor = 59;
  public static final int OF = 161;
  public static final int BY = 51;
  public static final int GROUP = 50;
  public static final int PRIMARY = 73;
  public static final int LEFT = 23;
  public static final int FOREIGN = 78;
  public static final int TABLE = 113;
  public static final int BOOLEAN = 105;
  public static final int NO = 126;
  public static final int DELETE = 18;
  public static final int Multiplicacion = 42;
  public static final int RIGHT = 24;
  public static final int AS = 26;
  public static final int BETWEEN = 65;
  public static final int FULL = 25;
  public static final int Diferente = 56;
  public static final int ALL = 48;
  public static final int MERGE = 32;
  public static final int EXISTS = 124;
  public static final int Resta = 41;
  public static final int ALTER = 129;
  public static final int NVARCHAR = 164;
  public static final int OUTER = 22;
  public static final int MAXSIZE = 155;
  public static final int Bit = 166;
  public static final int MB = 157;
  public static final int CASCADE = 84;
  public static final int HASH = 31;
  public static final int DATABASE = 85;
  public static final int SELECT = 47;
  public static final int FAST_FORWARD = 147;
  public static final int ROLLBACK = 138;
  public static final int TIME = 110;
  public static final int Int = 165;
  public static final int TOP = 4;
  public static final int TIMESTAMP = 111;
  public static final int LOOP = 30;
  public static final int VIEW = 93;
  public static final int SUM = 163;
  public static final int Arroba = 28;
  public static final int DATE = 106;
  public static final int FILE = 89;
  public static final int NOT = 63;
  public static final int SCROLL = 142;
  public static final int Corchete_de_apertura = 121;
  public static final int YEAR = 107;
  public static final int MIN = 162;
  public static final int Identificador = 9;
  public static final int PERCENT = 6;
  public static final int NONCLUSTERED = 76;
  public static final int JOIN = 20;
  public static final int DESC = 62;
  public static final int String = 45;
  public static final int TEXT = 114;
  public static final int OUTPUT = 10;
  public static final int MODULAR = 152;
  public static final int LONG = 116;
  public static final int FOR = 36;
  public static final int KB = 156;
  public static final int TRANSACTION = 134;
  public static final int AVG = 69;
  public static final int Menor_o_igual = 57;
  public static final int TRUNCATE = 130;
  public static final int INTEGER = 127;
  public static final int ROWGUIDCOL = 17;
  public static final int DOUBLE = 117;
  public static final int INSERT = 2;
  public static final int Parentesis_de_apertura = 7;
  public static final int COLUMN = 98;
  public static final int READ_ONLY = 148;
  public static final int INNER = 21;
  public static final int UNLIMITED = 154;
  public static final int FROM = 19;
  public static final int REFERENCES = 79;
  public static final int COLLATE = 87;
  public static final int PIVOT = 34;
  public static final int REPLICATION = 80;
  public static final int CONSTRAINT = 71;
  public static final int IS = 66;
  public static final int INDEX = 82;
  public static final int IN = 37;
  public static final int Menor = 60;
  public static final int DECLARE = 139;
  public static final int FORWARD_ONLY = 143;
  public static final int error = 1;
  public static final int FILENAME = 160;
  public static final int IF = 123;
  public static final int SCROLL_LOCKS = 149;
  public static final int STATIC = 144;
  public static final int DEFAULT = 11;
  public static final int Coma = 14;
  public static final int CLUSTERED = 75;
  public static final int SET = 39;
  public static final int CHECK = 81;
  public static final int OPTIMISTIC = 150;
  public static final int GLOBAL = 141;
  public static final int DISTINCT = 49;
  public static final int Punto_y_coma = 15;
  public static final int Mayor_o_igual = 58;
  public static final int UPDATE = 38;
  public static final int TRAN = 135;
  public static final int KEY = 74;
  public static final int Float = 46;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "INSERT",
  "INTO",
  "TOP",
  "VALUES",
  "PERCENT",
  "Parentesis_de_apertura",
  "Parentesis_de_cierre",
  "Identificador",
  "OUTPUT",
  "DEFAULT",
  "NULL",
  "Punto",
  "Coma",
  "Punto_y_coma",
  "GO",
  "ROWGUIDCOL",
  "DELETE",
  "FROM",
  "JOIN",
  "INNER",
  "OUTER",
  "LEFT",
  "RIGHT",
  "FULL",
  "AS",
  "ON",
  "Arroba",
  "Igual",
  "LOOP",
  "HASH",
  "MERGE",
  "REMOTE",
  "PIVOT",
  "UNPIVOT",
  "FOR",
  "IN",
  "UPDATE",
  "SET",
  "Suma",
  "Resta",
  "Multiplicacion",
  "Division",
  "Porcentaje",
  "String",
  "Float",
  "SELECT",
  "ALL",
  "DISTINCT",
  "GROUP",
  "BY",
  "ORDER",
  "HAVING",
  "AND",
  "ESCAPE",
  "Diferente",
  "Menor_o_igual",
  "Mayor_o_igual",
  "Mayor",
  "Menor",
  "ASC",
  "DESC",
  "NOT",
  "LIKE",
  "BETWEEN",
  "IS",
  "OR",
  "WHERE",
  "AVG",
  "COUNT",
  "CONSTRAINT",
  "IDENTITY",
  "PRIMARY",
  "KEY",
  "CLUSTERED",
  "NONCLUSTERED",
  "UNIQUE",
  "FOREIGN",
  "REFERENCES",
  "REPLICATION",
  "CHECK",
  "INDEX",
  "ACTION",
  "CASCADE",
  "DATABASE",
  "NAME",
  "COLLATE",
  "NAMES",
  "FILE",
  "FLOAT",
  "SIZE",
  "INCLUDE",
  "VIEW",
  "CREATE",
  "MODIFY",
  "CURRENT",
  "ADD",
  "COLUMN",
  "DROP",
  "CHAR",
  "BINARY",
  "BLOB",
  "BIT",
  "VARCHAR",
  "BOOLEAN",
  "DATE",
  "YEAR",
  "IMAGE",
  "REAL",
  "TIME",
  "TIMESTAMP",
  "CURSOR",
  "TABLE",
  "TEXT",
  "BYTE",
  "LONG",
  "DOUBLE",
  "NCHAR",
  "MAX",
  "USER",
  "Corchete_de_apertura",
  "Corchete_de_cierre",
  "IF",
  "EXISTS",
  "INT",
  "NO",
  "INTEGER",
  "SMALLINT",
  "ALTER",
  "TRUNCATE",
  "Numeral",
  "Doble_numeral",
  "BEGIN",
  "TRANSACTION",
  "TRAN",
  "COMMIT",
  "SAVEPOINT",
  "ROLLBACK",
  "DECLARE",
  "LOCAL",
  "GLOBAL",
  "SCROLL",
  "FORWARD_ONLY",
  "STATIC",
  "KEYSET",
  "DYNAMIC",
  "FAST_FORWARD",
  "READ_ONLY",
  "SCROLL_LOCKS",
  "OPTIMISTIC",
  "TYPE_WARNING",
  "MODULAR",
  "FILEGROWTH",
  "UNLIMITED",
  "MAXSIZE",
  "KB",
  "MB",
  "GB",
  "TB",
  "FILENAME",
  "OF",
  "MIN",
  "SUM",
  "NVARCHAR",
  "Int",
  "Bit"
  };
}

